### PR TITLE
Update mod-bspwm to PyQt5 from PyQt4

### PR DESCRIPTION
**Pull request by darvelo**
Hi! I really appreciate how you've written your code, it makes it really easy to read and understand.

I'm running Debian so I changed the shebang to `#!/usr/bin/env python3`. I think you're running Arch so I'm not sure if that applies.

I also added an `apt-get` installer to `libinstall.py` (let me know if you'd like to accept that feature) and I'm using that to install `pyqt5` so I'm not sure if my change to `__main__.py` will work for Arch. Testing is appreciated.

I also have a couple of patches on the way if you're interested.

I was moving away from lemonbar when I found this. Thanks for this great package!

### CODE REVIEW

**Comment by rr-** [comment]
Ha! I never expected a pull request to my own dotfiles.

I quickly tested the changes and noticed a minor problem with some of the event handlers, e.g. scrolling the mouse over the workspaces, volume control and mpd current track monitor throws exception:

    Traceback (most recent call last):
      File "/home/rr-/src/dotfiles/mod-bspwm/widgets/volume.py", line 64, in change_volume
        '1dB%s' % ['-', '+'][event.delta() > 0], 'unmute'])
    AttributeError: 'QWheelEvent' object has no attribute 'delta'

other than that, everything seems to work correctly.

**Comment by darvelo** [comment]
Haha, yeah, I guess that is kinda bizarre! Maybe you could split the panel out into its own repo, then you could call it: "barr-". :laughing: 

I believe I've fixed the mousewheel issue. I also included a couple of fixes in `widgets/window_title.py` that are needed for panel to work for me.

**Comment by rr-** [comment]
Thanks for the patches.

Regarding splitting the repo - I think I'll keep it here for time being.

**Comment by darvelo** [comment]
No problem. I think I'll split it out for my own dotfiles since I have a lot of changes, but I'll try to submit patches/features where I can. Thanks again.

**Pull request merged**
